# -*- coding: utf-8 -*-
"""docstring-to-code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FtZ3TRxJ1ZKWFH-qFQF9KKmAQCZG1e7M
"""

# !cp /content/drive/MyDrive/JuniorSemester2/CS181/docstring-to-code/gpt-2-finetuning/train.py /content/drive/MyDrive/JuniorSemester2/CS181/docstring-to-code/gpt-2-finetuning/src/train.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/JuniorSemester2/CS181/docstring-to-code/gpt-2-finetuning

!pip uninstall tensorflow

!pip install -r requirements.txt

# !python download_model.py 117M

!pip list

# Commented out IPython magic to ensure Python compatibility.
# %cd src

!python encode.py preprocess.txt preprocess.npz

!python train.py --dataset preprocess.npz

!python gen_output.py --temperature 0.5 --top_k 2 --model_name trained_model --filename "INPUT.txt"

